const restaurants = [
    {
    "info":{
    "id":"707067",
    "name":"Chinese Wok",
    "cloudinaryImageId":"e0839ff574213e6f35b3899ebf1fc597",
    "locality":"GST Main Road",
    "areaName":"Urapakkam",
    "costForTwo":"₹250 for two",
    "cuisines":[
    "Chinese",
    "Asian",
    "Tibetan",
    "Desserts"
    ],
    "avgRating":3.5,
    "parentId":"61955",
    "avgRatingString":"3.5",
    "totalRatingsString":"1.7K+",
    "sla":{
    "deliveryTime":37,
    "lastMileTravel":2.1,
    "serviceability":"SERVICEABLE",
    "slaString":"35-40 mins",
    "lastMileTravelString":"2.1 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-28 0000",
    "opened":true
    },
    "badges":{
    "imageBadges":[
    {
    "imageId":"bolt/big%20rx%20listing%2015%20mins%20.png",
    "description":"bolt!"
    },
    {
    "imageId":"Ratnesh_Badges/Rx_Awards_2025/Momo.png",
    "description":"Delivery!"
    }
    ],
    },
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{
    "badgeObject":[
    {
    "attributes":{
    "description":"bolt!",
    "imageId":"bolt/big%20rx%20listing%2015%20mins%20.png"
    }
    },
    {
    "attributes":{
    "description":"Delivery!",
    "imageId":"Ratnesh_Badges/Rx_Awards_2025/Momo.png"
    },
    }
    ]
    },
    "textBased":{},
    "textExtendedBadges":{},
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹129",
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--"
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/chinese-wok-gst-main-road-urapakkam-rest707067",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"396062",
    "name":"Pizza Hut",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2025/6/9/69312903-ad7d-4266-847f-5531f32eebc8_396062.JPG",
    "locality":"Potheri",
    "areaName":"Potheri",
    "costForTwo":"₹300 for two",
    "cuisines":[
    "Pizzas"
    ],
    "avgRating":3.7,
    "parentId":"721",
    "avgRatingString":"3.7",
    "totalRatingsString":"7.4K+",
    "sla":{
    "deliveryTime":32,
    "lastMileTravel":6.5,
    "serviceability":"SERVICEABLE",
    "slaString":"30-35 mins",
    "lastMileTravelString":"6.5 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-28 0000",
    "opened":true
    },
    "badges":{
    "imageBadges":[
    {
    "imageId":"Rxawards/_CATEGORY-Pizza.png",
    "description":"Delivery!"
    }
    ]
    },
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{
    "badgeObject":[
    {
    "attributes":{
    "description":"Delivery!",
    "imageId":"Rxawards/_CATEGORY-Pizza.png"
    }
    }
    ]
    },
    "textBased":{},
    "textExtendedBadges":{},
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹99",
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"4.3",
    "ratingCount":"1.3K+",
    },
    "source":"GOOGLE",
    "sourceIconImageId":"v1704440323/google_ratings/rating_google_tag"
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/pizza-hut-potheri-rest396062",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"227269",
    "name":"Burger King",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/936c6c55-c291-46cb-8ead-79960d02004b_227269.jpg",
    "locality":"Marimala Nagar",
    "areaName":"Kavanur",
    "costForTwo":"₹350 for two",
    "cuisines":[
    "Burgers",
    "American"
    ],
    "avgRating":4.4,
    "parentId":"166",
    "avgRatingString":"4.4",
    "totalRatingsString":"20K+",
    "sla":{
    "deliveryTime":26,
    "lastMileTravel":6,
    "serviceability":"SERVICEABLE",
    "slaString":"25-30 mins",
    "lastMileTravelString":"6.0 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-28 0000",
    "opened":true,
    },
    "badges":{},
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{},
    "textBased":{},
    "textExtendedBadges":{},
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹59",
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--"
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/burger-king-marimala-nagar-kavanur-rest227269",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"707068",
    "name":"Big Bowl",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2024/6/22/30548ac4-2e57-4c1d-ba73-8372f74a1ad2_707068.JPG",
    "locality":"GST Main Road",
    "areaName":"Urapakkam",
    "costForTwo":"₹250 for two",
    "cuisines":[
    "North Indian",
    "Chinese",
    "Tibetan",
    "Desserts"
    ],
    "avgRating":3.7,
    "parentId":"434792",
    "avgRatingString":"3.7",
    "totalRatingsString":"1.2K+",
    "sla":{
    "deliveryTime":34,
    "lastMileTravel":2.1,
    "serviceability":"SERVICEABLE",
    "slaString":"30-35 mins",
    "lastMileTravelString":"2.1 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-27 2000",
    "opened":true
    },
    "badges":{
    "imageBadges":[
    {
    "imageId":"bolt/big%20rx%20listing%2015%20mins%20.png",
    "description":"bolt!"
    }
    ]
    },
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{
    "badgeObject":[
    {
    "attributes":{
    "description":"bolt!",
    "imageId":"bolt/big%20rx%20listing%2015%20mins%20.png",
    }
    }
    ]
    },
    "textBased":{},
    "textExtendedBadges":{}
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹129"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--",
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/big-bowl-gst-main-road-urapakkam-rest707068",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"38912",
    "name":"Domino's Pizza",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2025/6/14/db4d963a-190f-4cd4-b220-b05088365581_38912.JPG",
    "locality":"GST Road",
    "areaName":"GST Road",
    "costForTwo":"₹400 for two",
    "cuisines":[
    "Pizzas",
    "Italian",
    "Pastas",
    "Desserts"
    ],
    "avgRating":3.7,
    "parentId":"2456",
    "avgRatingString":"3.7",
    "totalRatingsString":"11K+",
    "sla":{
    "deliveryTime":25,
    "lastMileTravel":1,
    "serviceability":"SERVICEABLE",
    "slaString":"20-25 mins",
    "lastMileTravelString":"1.0 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-27 259:00",
    "opened":true
    },
    "badges":{
    "imageBadges":[
    {
    "imageId":"Rxawards/_CATEGORY-Pizza.png",
    "description":"Delivery!"
    }
    ]
    },
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{
    "badgeObject":[
    {
    "attributes":{
    "description":"Delivery!",
    "imageId":"Rxawards/_CATEGORY-Pizza.png"
    }
    }
    ]
    },
    "textBased":{},
    "textExtendedBadges":{}
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹79"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--"
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/dominos-pizza-gst-road-rest38912",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"65248",
    "name":"McDonald's",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2025/6/3/f6491eff-6de8-4b92-9a95-5a65f7e054ce_65248.jpg",
    "locality":"Kanchipuram",
    "areaName":"Maraimalai Nagar",
    "costForTwo":"₹400 for two",
    "cuisines":[
    "Burgers",
    "Beverages",
    "Cafe",
    "Desserts"
    ],
    "avgRating":3.7,
    "parentId":"630",
    "avgRatingString":"3.7",
    "totalRatingsString":"18K+",
    "sla":{
    "deliveryTime":30,
    "lastMileTravel":10.3,
    "serviceability":"SERVICEABLE",
    "slaString":"30-35 mins",
    "lastMileTravelString":"10.3 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-28 0500",
    "opened":true
    },
    "badges":{
    "imageBadges":[
    {
    "imageId":"Rxawards/_CATEGORY-Burger.png",
    "description":"Delivery!"
    }
    ]
    },
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{
    "badgeObject":[
    {
    "attributes":{
    "description":"Delivery!",
    "imageId":"Rxawards/_CATEGORY-Burger.png"
    }
    }
    ]
    },
    "textBased":{},
    "textExtendedBadges":{}
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹119"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--",
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/mcdonalds-kanchipuram-maraimalai-nagar-rest65248",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"806199",
    "name":"KFC",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2024/12/9/b3d5ff48-4ea0-4b7f-b102-3c93b6349c3a_806199.JPG",
    "locality":"Kilampakkam",
    "areaName":"Urapakkam",
    "costForTwo":"₹400 for two",
    "cuisines":[
    "Burgers",
    "Fast Food",
    "Rolls & Wraps"
    ],
    "avgRating":4.3,
    "parentId":"547",
    "avgRatingString":"4.3",
    "totalRatingsString":"3.3K+",
    "sla":{
    "deliveryTime":14,
    "lastMileTravel":0.8,
    "serviceability":"SERVICEABLE",
    "slaString":"10-15 mins",
    "lastMileTravelString":"0.8 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-27 2000",
    "opened":true
    },
    "badges":{
    "imageBadges":[
    {
    "imageId":"bolt/big%20rx%20listing%2015%20mins%20.png",
    "description":"bolt!"
    },
    {
    "imageId":"Rxawards/_CATEGORY-Burger.png",
    "description":"Delivery!"
    }
    ]
    },
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{
    "badgeObject":[
    {
    "attributes":{
    "description":"bolt!",
    "imageId":"bolt/big%20rx%20listing%2015%20mins%20.png"
    }
    },
    {
    "attributes":{
    "description":"Delivery!",
    "imageId":"Rxawards/_CATEGORY-Burger.png"
    }
    }
    ]
    },
    "textBased":{},
    "textExtendedBadges":{}
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹59"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--"
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/kfc-kilampakkam-urapakkam-rest806199",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"745417",
    "name":"Subway",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2025/6/12/eef07d09-98d9-4094-99db-702b6fb0587c_745417.jpg",
    "locality":"Maraimalai Nagar",
    "areaName":"Guduvanchery",
    "costForTwo":"₹350 for two",
    "cuisines":[
    "sandwich",
    "Salads",
    "wrap",
    "Healthy Food"
    ],
    "avgRating":4,
    "parentId":"2",
    "avgRatingString":"4.0",
    "totalRatingsString":"1.5K+",
    "sla":{
    "deliveryTime":26,
    "lastMileTravel":6.5,
    "serviceability":"SERVICEABLE",
    "slaString":"25-30 mins",
    "lastMileTravelString":"6.5 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-28 0000",
    "opened":true
    },
    "badges":{},
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{},
    "textBased":{},
    "textExtendedBadges":{}
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹119"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--"
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/subway-maraimalai-nagar-guduvanchery-rest745417",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"43997",
    "name":"A2B - Adyar Ananda Bhavan",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2025/1/15/ba165688-6f98-437d-9cbb-22fec02ec0fd_43997.jpg",
    "locality":"Guduvancherry",
    "areaName":"Kavanur",
    "costForTwo":"₹300 for two",
    "cuisines":[
    "South Indian",
    "Sweets",
    "Chinese"
    ],
    "avgRating":4.4,
    "veg":true,
    "parentId":"22",
    "avgRatingString":"4.4",
    "totalRatingsString":"59K+",
    "sla":{
    "deliveryTime":34,
    "lastMileTravel":6,
    "serviceability":"SERVICEABLE",
    "slaString":"30-35 mins",
    "lastMileTravelString":"6.0 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-27 259:00",
    "opened":true
    },
    "badges":{
    "imageBadges":[
    {
    "imageId":"Rxawards/_CATEGORY-South%20Indian.png",
    "description":"Delivery!"
    }
    ]
    },
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{
    "badgeObject":[
    {
    "attributes":{
    "description":"Delivery!",
    "imageId":"Rxawards/_CATEGORY-South%20Indian.png"
    }
    }
    ]
    },
    "textBased":{},
    "textExtendedBadges":{}
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"₹200 OFF",
    "subHeader":"ABOVE ₹499",
    "discountTag":"FLAT DEAL"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--"
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/a2b-adyar-ananda-bhavan-guduvancherry-kavanur-rest43997",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"103124",
    "name":"LunchBox - Meals and Thalis",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2024/10/16/ed7a0ca5-f8a7-4f1d-9042-b59fd288cc2c_103124.jpg",
    "locality":"GST main road",
    "areaName":"Urapakkam",
    "costForTwo":"₹200 for two",
    "cuisines":[
    "Thalis",
    "North Indian",
    "Biryani"
    ],
    "avgRating":4.6,
    "parentId":"4925",
    "avgRatingString":"4.6",
    "totalRatingsString":"11K+",
    "sla":{
    "deliveryTime":27,
    "lastMileTravel":3,
    "serviceability":"SERVICEABLE",
    "slaString":"25-30 mins",
    "lastMileTravelString":"3.0 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-27 259:00",
    "opened":true
    },
    "badges":{},
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{},
    "textBased":{},
    "textExtendedBadges":{}
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹99"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--",
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/lunchbox-meals-and-thalis-gst-main-road-urapakkam-rest103124",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"103118",
    "name":"Faasos - Wraps, Rolls & Shawarma",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2024/7/28/1d122a2e-b372-4a4d-b793-f3345149cf17_103118.JPG",
    "locality":"GST main road",
    "areaName":"Urapakkam",
    "costForTwo":"₹200 for two",
    "cuisines":[
    "Kebabs",
    "Fast Food",
    "Snacks",
    "American",
    "Healthy Food",
    "Desserts",
    "Beverages"
    ],
    "avgRating":4.4,
    "parentId":"21809",
    "avgRatingString":"4.4",
    "totalRatingsString":"11K+",
    "sla":{
    "deliveryTime":30,
    "lastMileTravel":3,
    "serviceability":"SERVICEABLE",
    "slaString":"25-30 mins",
    "lastMileTravelString":"3.0 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-27 259:00",
    "opened":true
    },
    "badges":{
    "imageBadges":[
    {
    "imageId":"Rxawards/_CATEGORY-Rolls.png",
    "description":"Delivery!"
    }
    ]
    },
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{
    "badgeObject":[
    {
    "attributes":{
    "description":"Delivery!",
    "imageId":"Rxawards/_CATEGORY-Rolls.png"
    }
    }
    ]
    },
    "textBased":{},
    "textExtendedBadges":{}
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹69"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--",
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/faasos-wraps-rolls-and-shawarma-gst-main-road-urapakkam-rest103118",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"156169",
    "name":"The Good Bowl",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2024/11/15/6d664682-c5aa-4a43-8cd3-95b8b45aabdd_156169.jpg",
    "locality":"MIT Colony",
    "areaName":"Urapakkam",
    "costForTwo":"₹400 for two",
    "cuisines":[
    "Biryani",
    "North Indian",
    "Pastas",
    "Punjabi",
    "Desserts",
    "Beverages"
    ],
    "avgRating":4.5,
    "parentId":"7918",
    "avgRatingString":"4.5",
    "totalRatingsString":"3.3K+",
    "sla":{
    "deliveryTime":27,
    "lastMileTravel":3,
    "serviceability":"SERVICEABLE",
    "slaString":"25-30 mins",
    "lastMileTravelString":"3.0 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-27 259:00",
    "opened":true
    },
    "badges":{},
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{},
    "textBased":{},
    "textExtendedBadges":{}
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹99"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--",
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/the-good-bowl-mit-colony-urapakkam-rest156169",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"864534",
    "name":"Wow! Momo",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2025/6/30/70a77c02-dae2-446a-96f0-77fb86db612e_864534.jpg",
    "locality":"Anna Nagar",
    "areaName":"Kolapakkam",
    "costForTwo":"₹300 for two",
    "cuisines":[
    "Momos",
    "Chinese",
    "fastfood",
    "Asian",
    "Beverages"
    ],
    "avgRating":4.3,
    "parentId":"1776",
    "avgRatingString":"4.3",
    "totalRatingsString":"890",
    "sla":{
    "deliveryTime":34,
    "lastMileTravel":5,
    "serviceability":"SERVICEABLE",
    "slaString":"30-35 mins",
    "lastMileTravelString":"5.0 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-28 0000",
    "opened":true
    },
    "badges":{
    "imageBadges":[
    {
    "imageId":"Ratnesh_Badges/Rx_Awards_2025/Momo.png",
    "description":"Delivery!"
    }
    ]
    },
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{
    "badgeObject":[
    {
    "attributes":{
    "description":"Delivery!",
    "imageId":"Ratnesh_Badges/Rx_Awards_2025/Momo.png"
    }
    }
    ]
    },
    "textBased":{},
    "textExtendedBadges":{}
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹69"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--",
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/wow-momo-anna-nagar-kolapakkam-rest864534",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"50974",
    "name":"Buhari Hotel",
    "cloudinaryImageId":"ibvf25to8c5vr25tah5b",
    "locality":"urappakkam",
    "areaName":"Urapakkam",
    "costForTwo":"₹400 for two",
    "cuisines":[
    "Biryani",
    "North Indian",
    "Chinese"
    ],
    "avgRating":4.3,
    "parentId":"50838",
    "avgRatingString":"4.3",
    "totalRatingsString":"5.9K+",
    "sla":{
    "deliveryTime":28,
    "lastMileTravel":2.8,
    "serviceability":"SERVICEABLE",
    "slaString":"25-30 mins",
    "lastMileTravelString":"2.8 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-27 2000",
    "opened":true
    },
    "badges":{},
    "isOpen":true,
    "aggregatedDiscountInfoV2":{},
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{},
    "textBased":{},
    "textExtendedBadges":{},
    }
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"3.5",
    "ratingCount":"3.6K+"
    },
    "source":"GOOGLE",
    "sourceIconImageId":"v1704440323/google_ratings/rating_google_tag"
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/buhari-hotel-urappakkam-urapakkam-rest50974",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"191532",
    "name":"The Biryani Life",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2024/6/15/64a1da6d-3c5e-49fc-b8ee-93fc9f90f9b1_191532.jpg",
    "locality":"GST main road",
    "areaName":"Urapakkam",
    "costForTwo":"₹250 for two",
    "cuisines":[
    "Biryani",
    "Mughlai",
    "Lucknowi",
    "Hyderabadi",
    "Kebabs",
    "Desserts",
    "Beverages"
    ],
    "avgRating":3.7,
    "parentId":"8496",
    "avgRatingString":"3.7",
    "totalRatingsString":"2.7K+",
    "sla":{
    "deliveryTime":29,
    "lastMileTravel":3,
    "serviceability":"SERVICEABLE",
    "slaString":"25-30 mins",
    "lastMileTravelString":"3.0 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-27 259:00",
    "opened":true
    },
    "badges":{},
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{},
    "textBased":{},
    "textExtendedBadges":{}
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹149"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{},
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--",
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/the-biryani-life-gst-main-road-urapakkam-rest191532",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"46841",
    "name":"Sangeetha Veg Restaurant",
    "cloudinaryImageId":"cswrdoqdwi0hpw09d54j",
    "locality":"GST Road",
    "areaName":"Urapakkam",
    "costForTwo":"₹600 for two",
    "cuisines":[
    "South Indian",
    "North Indian",
    "Chinese"
    ],
    "avgRating":4.6,
    "parentId":"1260",
    "avgRatingString":"4.6",
    "totalRatingsString":"42K+",
    "sla":{
    "deliveryTime":32,
    "lastMileTravel":5.5,
    "serviceability":"SERVICEABLE",
    "slaString":"30-35 mins",
    "lastMileTravelString":"5.5 km",
    "iconType":"ICON_TYPE_EMPTY",
    },
    "availability":{
    "nextCloseTime":"2025-07-27 2000",
    "opened":true
    },
    "badges":{},
    "isOpen":true,
    "aggregatedDiscountInfoV2":{},
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{},
    "textBased":{},
    "textExtendedBadges":{}
    }
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{},
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"4.0",
    "ratingCount":"11K+"
    },
    "source":"GOOGLE",
    "sourceIconImageId":"v1704440323/google_ratings/rating_google_tag"
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/sangeetha-veg-restaurant-gst-road-urapakkam-rest46841",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"103119",
    "name":"Behrouz Biryani",
    "cloudinaryImageId":"RX_THUMBNAIL/IMAGES/VENDOR/2024/6/15/7d7d3d2a-f530-4786-a965-9f1c3c643c15_103119.jpg",
    "locality":"GST main road",
    "areaName":"Urapakkam",
    "costForTwo":"₹500 for two",
    "cuisines":[
    "Biryani",
    "Kebabs",
    "Mughlai",
    "Lucknowi",
    "Hyderabadi",
    "Desserts",
    "Beverages"
    ],
    "avgRating":4.4,
    "parentId":"1803",
    "avgRatingString":"4.4",
    "totalRatingsString":"4.0K+",
    "sla":{
    "deliveryTime":38,
    "lastMileTravel":3,
    "serviceability":"SERVICEABLE",
    "slaString":"35-40 mins",
    "lastMileTravelString":"3.0 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-27 259:00",
    "opened":true
    },
    "badges":{
    "imageBadges":[
    {
    "imageId":"newg.png",
    "description":"Gourmet"
    }
    ]
    },
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{
    "badgeObject":[
    {
    "attributes":{
    "description":"Gourmet",
    "imageId":"newg.png"
    }
    }
    ]
    },
    "textBased":{},
    "textExtendedBadges":{},
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹199"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{},
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--",
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/behrouz-biryani-gst-main-road-urapakkam-rest103119",
    "type":"WEBLINK"
    }
    },
    {
    "info":{
    "id":"566300",
    "name":"Faasos' Signature Wraps & Rolls",
    "cloudinaryImageId":"c583ca6ce40b426797a78ae2ac91f2ec",
    "locality":"GST main road",
    "areaName":"Urapakkam",
    "costForTwo":"₹350 for two",
    "cuisines":[
    "Fast Food",
    "Snacks",
    "North Indian",
    "Desserts",
    "Beverages"
    ],
    "avgRating":4.4,
    "parentId":"340366",
    "avgRatingString":"4.4",
    "totalRatingsString":"205",
    "sla":{
    "deliveryTime":30,
    "lastMileTravel":3,
    "serviceability":"SERVICEABLE",
    "slaString":"30-35 mins",
    "lastMileTravelString":"3.0 km",
    "iconType":"ICON_TYPE_EMPTY"
    },
    "availability":{
    "nextCloseTime":"2025-07-27 259:00",
    "opened":true
    },
    "badges":{
    "textExtendedBadges":[
    {
    "iconId":"guiltfree/GF_Logo_android_3x",
    "shortDescription":"options available",
    "fontColor":"#7E808C"
    }
    ]
    },
    "isOpen":true,
    "type":"F",
    "badgesV2":{
    "entityBadges":{
    "imageBased":{},
    "textBased":{},
    "textExtendedBadges":{
    "badgeObject":[
    {
    "attributes":{
    "description":"",
    "fontColor":"#7E808C",
    "iconId":"guiltfree/GF_Logo_android_3x",
    "shortDescription":"options available",
    }
    }
    ]
    }
    }
    },
    "aggregatedDiscountInfoV3":{
    "header":"ITEMS",
    "subHeader":"AT ₹129"
    },
    "differentiatedUi":{
    "displayType":"ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
    "differentiatedUiMediaDetails":{
    "lottie":{},
    "video":{}
    }
    },
    "reviewsSummary":{},
    "displayType":"RESTAURANT_DISPLAY_TYPE_DEFAULT",
    "restaurantOfferPresentationInfo":{},
    "externalRatings":{
    "aggregatedRating":{
    "rating":"--",
    }
    },
    "ratingsDisplayPreference":"RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    },
    "analytics":{
    "context":"seo-data-9af6a172-bde5-434f-9a93-c3c50b868cf8"
    },
    "cta":{
    "link":"https://www.swiggy.com/city/chennai/faasos-signature-wraps-and-rolls-gst-main-road-urapakkam-rest566300",
    "type":"WEBLINK"
    }
    }
    ];

    export default restaurants;

    